remote_theme: klaudiosinani/re@v0.3.0
plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme
  - jekyll-sitemap

re:
  favicon: https://raw.githubusercontent.com/klaudiosinani/klaudiosinani.github.io/refs/heads/master/public/favicon.png
